name: 'ci'

on:
  - 'push'
  - 'pull_request'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v1'

    - run: 'npm ci'
    - run: 'npm run prettier'
    - run: 'npm run eslint'
    - run: 'npm run build'
    - run: 'npm test'
    - uses: ./
      with:
        milliseconds: 1000
