---
name: 'prerelease'

on:
  push:
    branches:
      - 'master'

jobs:
  prerelease:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v1'

      - name: 'Update git remotes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

      - name: 'Generate the "latest" release'
        run: './scripts/release.sh latest'
