---
name: "keybase"

on:
  watch:
    types:
      - "started"
  push:
  pull_request:
    types:
      - "opened"
      - "closed"
      - "reopened"
      - "synchronize"
  commit_comment:

  # Not yet implemented
  fork:
  issue_comment:
  issues:

jobs:
  keybase:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/actions/packages/keybase-notifications@latest"
        with:
          keybase_username: "${{ secrets.KeybaseUsername }}"
          keybase_paper_key: "${{ secrets.KeybasePaperKey }}"
          keybase_team_name: "${{ secrets.KeybaseTeamName }}"
          keybase_topic_name: "${{ secrets.KeybaseTopicName }}"
