---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          lfs: true

      - name: "Install and build"
        run: |
          yarn run reinstall
          yarn run build

      - uses: "./packages/automatic-releases/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            packages/automatic-releases/dist/index.js
            packages/keybase-notifications/dist/index.js
            packages/keybase-notifications/dist/keybase
