---
name: "prerelease"

on:
  push:
    branches:
      - "automatic-pre-releaser"
    tags:
      - "v*"

jobs:
  prerelease:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          lfs: true

      - name: "Install and build"
        run: |
          yarn run reinstall
          yarn run build

      - uses: "./packages/automatic-releases/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
